spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/finsall_micro
    password: seenu@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
